name: Test Package
on: push

jobs:
  build:
    runs-on: ubuntu-18.04
    container: rocker/verse:latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages(c('remotes', 'covr'), repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"

      - name: Check Package
        run: Rscript -e "devtools::check()"
        env:
          osu_api: ${{secrets.osu_api}}

      - name: Code Coverage
        run: Rscript -e "covr::codecov(quiet = FALSE, commit = '$GITHUB_SHA', branch = '$GITHUB_REF', token = '$${{ secrets.CODECOV_TOKEN }}')"
        env:
          osu_api: ${{secrets.osu_api}}

