name: Test
'on': push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v1

      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"

      - name: Check Package
        run: Rscript -e "devtools::check()"
        with:
          osu_api: ${{secrets.osu_api}}
    container: rocker/verse:latest
