name: Test
'on': push

jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
      - name: Update image
        run: sudo apt-get update && apt-get upgrade

      - name: Checkout Repository
        uses: actions/checkout@master

      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
    container: rocker/verse:latest
